name: Build Armbian

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: winddyx/armbian-compile-action@main
        with:
          board: nanopineo
          distro: debian
          suite: trixie
          flavor: cli
          artifacts: 'true'
